name: flutter_base
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #base UI
  cupertino_icons: ^0.1.3
  cached_network_image: ^2.2.0+1
  flutter_spinkit: "^4.1.2"
  flutter_icons: ^1.1.0
  fl_chart: ^0.11.1

  #core
  equatable: ^1.2.0
  dartz: ^0.9.1
  provider: ^4.0.4
  shared_preferences: ^0.5.4+9
  rxdart: ^0.24.1
  sprintf: ^4.0.2
  logger: 0.9.1
  intl: ^0.16.1

  #di
  get_it: ^4.0.2

  #network
  dio: ^3.0.4
  retrofit: ^1.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  json_serializable: ^3.3.0
  retrofit_generator: ^1.0.2+2

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/languages/

